server {
    listen 80;
    listen [::]:80;
    server_name words.rfdsx.online;

    location ^~ /.well-known/acme-challenge/ {
        proxy_pass http://siss-acme-web:80;
        proxy_set_header Host $host;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
