import { test, expect } from '@playwright/test'

test('isolated browser: words, policy, actual typing, reload recovery, reports, archive', async ({ page }) => {
  await page.request.post('/api/test-reset', { headers: { 'X-WordLearner-Request': '1' } })
  await page.route('**/api/lookup?*', route => route.fulfill({ json: { word: new URL(route.request().url()).searchParams.get('word'), translation: '', phonetic: '[test]', warning: '' } }))
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  const ownerHeaders = { 'X-WordLearner-Page': await page.evaluate(() => sessionStorage.getItem('wordlearner-page-id') || '') }
  await expect(page.getByText('从第一个单词开始')).toBeVisible()
  await expect(page.locator('.summary-line')).toContainText('累计复习 00:00:00')
  for (const [word, translation] of [['cat', '猫'], ['sun', '太阳']]) {
    await page.getByLabel('英文', { exact: true }).fill(word)
    await page.getByLabel('释义', { exact: true }).fill(translation)
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByText(`已保存：${word}`, { exact: true })).toBeVisible()
  }
  await expect(page.locator('.word-table tbody tr')).toHaveCount(2)
  await page.screenshot({ path: '../test-results/words.png', fullPage: true })
  await page.getByRole('button', { name: '家长设置', exact: true }).click()
  await page.getByLabel('设置家长密码（至少 6 位）').fill('e2e-parent123')
  await page.getByLabel('再次输入密码').fill('e2e-parent123')
  await page.getByRole('button', { name: '保存设置' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByLabel('选择 cat', { exact: true }).check()
  const created = page.waitForResponse(response => response.url().endsWith('/api/games') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '开始练习', exact: true }).click()
  const jobId = (await (await created).json()).job_id
  let id = ''
  await expect.poll(async () => { const job = await (await page.request.get(`/api/jobs/${jobId}`, { headers: ownerHeaders })).json(); id = job.result.id; return job.status }).toBe('completed')
  const game = async () => (await page.request.get(`/api/games/${id}`, { headers: ownerHeaders })).json()
  await expect.poll(async () => (await game()).active.length).toBe(1)
  await page.locator('canvas').click({ position: { x: 400, y: 400 } })
  await page.keyboard.type('c', { delay: 90 })
  await expect.poll(async () => (await game()).active[0]?.progress).toBe(1)
  await page.screenshot({ path: '../test-results/game.png', fullPage: true })
  await page.reload()
  await expect(page.getByRole('button', { name: '恢复进度', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '恢复进度', exact: true }).click()
  await expect.poll(async () => (await game()).status).toBe('running')
  await page.locator('canvas').click({ position: { x: 400, y: 400 } })
  await page.keyboard.type('at', { delay: 90 })
  await expect.poll(async () => (await game()).score).toBe(10)
  await page.getByRole('button', { name: '保存并返回' }).click()
  await expect(page.getByRole('heading', { name: '单词学习', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '每日报告', exact: true }).first().click()
  await expect(page.getByRole('dialog', { name: '每日报告' })).toBeVisible()
  await page.getByRole('button', { name: '历史记录', exact: true }).click()
  await expect(page.locator('.report-table tbody tr')).toHaveCount(1)
  await expect(page.locator('.report-table')).toContainText('cat')
  await expect(page.locator('.report-table')).toContainText('正确')
  await page.screenshot({ path: '../test-results/report.png', fullPage: true })
  await page.getByRole('button', { name: '关闭窗口' }).click()
  await page.getByLabel('选择 cat', { exact: true }).check()
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除', exact: true }).click()
  await expect(page.locator('.word-table tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: '每日报告', exact: true }).first().click()
  await page.getByRole('button', { name: '历史记录', exact: true }).click()
  await expect(page.locator('.report-table')).toContainText('cat')
  await page.getByRole('button', { name: '关闭窗口' }).click()
  const beforeDebug = await (await page.request.get('/api/bootstrap', { headers: ownerHeaders })).json()
  expect(beforeDebug.summary.review_usage_seconds).toBe(0)
  const historyBefore = await (await page.request.get('/api/reports', { headers: ownerHeaders })).json()
  await page.getByLabel('免麦克风复习模式').check()
  await page.getByLabel('选择 sun', { exact: true }).check()
  const debugCreated = page.waitForResponse(response => response.url().endsWith('/api/games') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '开始练习', exact: true }).click()
  const debugJobId = (await (await debugCreated).json()).job_id
  let debugId = ''
  await expect.poll(async () => { const job = await (await page.request.get(`/api/jobs/${debugJobId}`, { headers: ownerHeaders })).json(); debugId = job.result.id; return job.status }).toBe('completed')
  const debugGame = async () => (await page.request.get(`/api/games/${debugId}`, { headers: ownerHeaders })).json()
  await expect.poll(async () => (await debugGame()).active.length).toBe(1)
  expect((await debugGame()).mode).toBe('debug')
  await expect(page.getByRole('button', { name: '按住测试麦克风' })).toBeVisible()
  await expect(page.getByText('麦克风测试只显示结果，不锁定单词')).toBeVisible()
  await page.locator('canvas').focus()
  await page.keyboard.type('sun', { delay: 60 })
  await expect.poll(async () => (await debugGame()).score).toBe(10)
  await expect.poll(async () => { const state = await debugGame(); return state.round === 2 && state.active.length === 1 }).toBe(true)
  await page.locator('canvas').focus()
  await page.keyboard.type('sun', { delay: 60 })
  await expect.poll(async () => { const state = await debugGame(); return state.round === 3 && state.active.length === 1 }).toBe(true)
  expect((await debugGame()).status).toBe('running')
  expect((await debugGame()).saved_reward_money).toBe(4)
  await page.getByRole('button', { name: '保存并返回' }).click()
  await expect(page.getByRole('heading', { name: '单词学习', exact: true })).toBeVisible()
  const afterDebug = await (await page.request.get('/api/bootstrap', { headers: ownerHeaders })).json()
  expect(afterDebug.summary.total_score).toBe(beforeDebug.summary.total_score + 20)
  expect(afterDebug.summary.review_usage_seconds).toBeGreaterThan(0)
  expect(afterDebug.summary.usage_seconds).toBe(afterDebug.summary.review_usage_seconds)
  expect((await (await page.request.get('/api/reports', { headers: ownerHeaders })).json()).history_total).toBe(historyBefore.history_total + 2)
  expect(errors).toEqual([])
})
